[theme]
primaryColor = "#00ff00"             # Neon green for highlights and buttons
backgroundColor = "#000000"          # Dark background to make neon colors pop
secondaryBackgroundColor = "#333333" # Slightly lighter black for sidebar and panels
textColor = "#ffffff"                # White text for contrast
font = "monospace"                   # Monospace font for a techy feel

[browser]
gatherUsageStats = false             # Disable usage stats collection
serverPort = 8501                # Default server port